### ISSUE TITLE
Lege Offerte opslaan

### ISSUE THREAD

**Issue by EllenVanEygen** [bbastiaensen/Mia#105]
Als je een offerte probeert op te slaan zonder een offerte mee te geven geeft die een foutboodschap je moet eerst een offerte selecteren. hierna krijg je de melding Je aanvraag is succesvol opgeslagen. Hierna krijg je de error er is een fout gebeurt tijdens het opslaan van de offerte Object reference not set to an instance of an object.

**Comment by bbastiaensen** [comment]
2 situaties:
Bij het toevoegen van offertes bij een nieuwe aanvraag. => Zorgen dat we niet meer in de null reference situatie komen.
Bij het toevoegen van offertes bij een bestaande aanvraag. => Na de foutboodschap mag de bevestigingsboodschap niet meer komen.
