### ISSUE TITLE
In gebruikersbeheer mensen op actief zetten

### ISSUE THREAD

**Issue by Timzz04** [bbastiaensen/Mia#107]
Als je een gebruiker op niet actief wilt zetten wordt die automatish terug op actief gezet.
het is de bedoeling dat je oude gebruikers die op niet actief zet niet op de app mogen maar nieuwe gebruikers automatisch op actief worden gezet met de rol aanvrager

**Comment by bbastiaensen** [comment]
Was nog niet ok. Nu werd de gebruiker altijd op niet actief gezet. Onafhankelijk van wat de waarde in de checkbox was. Nu opgelost.
