### ISSUE TITLE
Numerieke waarden bij filters op lijst aanvragen

### ISSUE THREAD

**Issue by bbastiaensen** [bbastiaensen/Mia#109]
Het is inderdaad niet mogelijk om letters in te geven bij bedragen van de "Van" en "Tot" filter op de lijst met aanvragen. Maar dit kan beter. Volgende aanpassingen moeten gemaakt worden:

1. decimale tekens (. en ,) moeten wel mogelijk zijn.
2. Als er andere tekens dan cijfers en decimale tekens worden ingetypt worden deze nkiet getoond in het tekstvak. Er hoeft geen foutboodschap te zijn.

Idem voor het financieringsjaar:
1. decimale tekens (. en ,) mogen NIET mogelijk zijn.
2. Als er andere tekens dan cijfers en decimale tekens worden ingetypt worden deze nkiet getoond in het tekstvak. Er hoeft geen foutboodschap te zijn.

**Comment by EllenVanEygen** [comment]
klaar

**Comment by bbastiaensen** [comment]
Nog niet helemaal. Als ik bij financieringsjaar al cijfers heb ingetypt en ik typ dan letters in, dan verdwijnen ook de reeds ingetypte cijfers. Deze moeten behouden blijven.

**Comment by EllenVanEygen** [comment]
klaar
