### ISSUE TITLE
Filteren op bedragen in lijst aanvragen

### ISSUE THREAD

**Issue by bbastiaensen** [bbastiaensen/Mia#110]
Als ik bijvoorbeeld 500 in de filter bedragen bij "Van" zet, en ik vink deze filter aan dan komen er na filtering ook aanvragen te staan met een bedrag kleiner dan 500. Idem voor de "Tot" filter. Pas als ik beide filters samen aanzet is de filtering correct. Dit moet aangepast worden.

1. De "Van" filter moet losstaand werken
2. De "Tot" filter moet losstaand werken
3. De combinatie van beide filters moet ook blijven werken.

**Comment by EllenVanEygen** [comment]
klaar
