### ISSUE TITLE
Filter parameters

### ISSUE THREAD

**Issue by EllenVanEygen** [bbastiaensen/Mia#52]
1) Als je een nieuwe parameter ingeeft en dan filterd worden de velden terug leeg gemaakt. Moeten we hier niet eerst vragen of ze de parameter willen opslaan
2) Als je filterd en dan een nieuwe parameter wilt bewaaren geeft die een error input string was not in a correct format.

**Comment by bbastiaensen** [comment]
1. Ja, dit mag zo aangepast worden
2. Fixen
