### ISSUE TITLE
AanvraagFormulier foutboodschap

### ISSUE THREAD

**Issue by EllenVanEygen** [bbastiaensen/Mia#60]
De foudboodschap als je wie koopt het niet ingeeft is aankoper is verplicht.
Of de foutboodschap moet aangepast worden naar wie koopt het is verplicht.
Of Wie koopt het moet aangepast worden naar aankoper.

**Comment by bbastiaensen** [comment]
Ellen, leg eens duidelijker uit wat de situatie is. Want ik ben niet helemaal mee.

**Comment by EllenVanEygen** [comment]
Dus als je in het aanvraagformulier bij nieuwe aanvraag Wie koopt het leeg laat komt er de foutmelding dat Aankoper verplicht is.
Op het Aanvraagformulier noemt dit veld Wie koopt het.
