### ISSUE TITLE
Fout Foto's opslaan

### ISSUE THREAD

**Issue by EllenVanEygen** [bbastiaensen/Mia#61]
Als je een foto wilt opslaan dan komt er een error:
![Screenshot 2024-03-25 084016](https://github.com/bbastiaensen/Mia/assets/123730604/6897c29f-f864-4bf6-b46a-19c03e91caeb)
En daarna zecht die dat het is opgeslagen maar als ik in de databank ga kijken geeft die een andere URL bij het aanvraag nummer van de aanvraag.
![Screenshot 2024-03-25 084044](https://github.com/bbastiaensen/Mia/assets/123730604/070fae5a-6d8d-43b6-a59f-7a94d0f311c8)

**Comment by bbastiaensen** [comment]
Er spelen hier 2 zaken:

1. Enerzijds is er het eerste deel van de url die gaat verwijzen naar de centrale fileserver van Muylenberg. Om te testen kunnen we hiervoor misschien zelf een testfolder op OneDrive gebruiken. (maar niet op die van het project, maak eventueel een specifieke daarvoor aan)
2. Anderzijds bewaren we in de url van de foto NIET de volledige url. Enkel het gedeelte van na de url uit puntje 1

**Comment by Timzz04** [comment]
Exact hetzelfde hier als bij de offertes bug. De bedoeling is dat we in de active directory c:/Muylenberg gaan hebben (of zoiets) Mijn code voegt hier oftewel / fotos oftewel /offertes bij en past dan de naam van het bestand aan, maar voor te testen heb ik een andere parameter gebruikt
