### ISSUE TITLE
Fout opslaan Offertes

### ISSUE THREAD

**Issue by EllenVanEygen** [bbastiaensen/Mia#62]
Als je een foto wilt opslaan dan komt er een error:

![Screenshot 2024-03-25 084233](https://github.com/bbastiaensen/Mia/assets/123730604/77981273-360e-448f-9488-dcbf74424725)

**Comment by bbastiaensen** [comment]
Er spelen hier 2 zaken:

1. Enerzijds is er het eerste deel van de url die gaat verwijzen naar de centrale fileserver van Muylenberg. Om te testen kunnen we hiervoor misschien zelf een testfolder op OneDrive gebruiken. (maar niet op die van het project, maak eventueel een specifieke daarvoor aan)
2. Anderzijds bewaren we in de url van de offerte NIET de volledige url. Enkel het gedeelte van na de url uit puntje 1

**Comment by Timzz04** [comment]
Dit is geen bug, dit is omdat ik om te testen een nieuwe parameter genaamd testmap (C:\Users\TimMeeus\OneDrive - Scholengroep Fluxus\Bureaublad\TestMapFotos) toegevoegd had omdat ik geen c:/Folder had. Ik moet gewoon de parameternaam aanpassen wanneer we het testen op de activedirectory om dit te fixen.
Dit is wat het nu is : mainPath = ParameterManager.GetParameterByCode("Testmap").Waarde; en die testmap moet aangepast worden naar FotoMap
